# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        build: ./images/nginx
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - postgresql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www

    postgresql:
        container_name: postgresql
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sait
        volumes:
            - ./db-data/postgres-data:/var/lib/postgresql/data
            - type: bind
              source: ./db-data/postgres-migrations/001-create-table-users.sql
              target: /docker-entrypoint-initdb.d/1-create-users.sql
              read_only: true
            - type: bind
              source: ./db-data/postgres-migrations/002-insert-users.sql
              target: /docker-entrypoint-initdb.d/2-insert-users.sql
              read_only: true

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.com
            PGADMIN_DEFAULT_PASSWORD: admin_password
        ports:
            - "5050:80"
        volumes:
            - ./db-data/pgadmin-data:/var/lib/pgadmin
        links:
            - postgresql
